project:
  title: "The Carpentries Workbench"
  type: website

format:
  html:
    from: markdown+emoji
    toc: true
    include-in-header: assets/workbench-tools.html
    filters:
      - assets/workbench-filters.lua

book:
  title: "The Carpentries Workbench"
  author: "Zhian N. Kamvar"
  date: "2022-04-29"
  chapters:
    - index.qmd
    - transition-guide.qmd
    - releases.qmd

website:
  title: "The Carpentries Workbench"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      - text: Guides
        menu:
          - text: How The Workbench Works
            href: workflow-guide.qmd
          - text: Transition Guide
            href: transition-guide.qmd
          - text: "Developer's Guide (external)"
            href: https://carpentries.github.io/workbench-dev
    right:
      - icon: github
        href: 'https://github.com/carpentries/workbench'
        aria-label: Workbench GitHub





