project:
  title: "Workbench this and that"
  type: website

format:
  html:
    toc: true

book:
  title: "Workbench This and That"
  author: "Zhian N. Kamvar"
  date: "2022-04-29"
  chapters:
    - index.qmd
    - transition-guide.qmd

website:
  title: "Workbench This and That"
  background: primary
  navbar:
    left:
      - href: transition-guide.qmd
        text: Transition Guide





