project:
  title: "The Carpentries Workbench"
  type: website

format:
  html:
    toc: true

book:
  title: "Workbench This and That"
  author: "Zhian N. Kamvar"
  date: "2022-04-29"
  chapters:
    - index.qmd
    - transition-guide.qmd
    - releases.qmd

website:
  title: "The Carpentries Workbench"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      - href: beta-phase.qmd
        text: "**Beta Phase**"
      - href: workflow-guide.qmd
        text: How The Workbench Works
      - href: transition-guide.qmd
        text: Transition Guide
      - text: "Contributor Guides"
        menu:
         - contributor/index.qmd
         - contributor/releases.qmd
    right:
      - icon: github
        href: 'https://github.com/carpentries/workbench'
        aria-label: Workbench GitHub





