project:
  title: "The Carpentries Workbench"
  type: website

format:
  html:
    from: markdown+emoji
    toc: true
    include-in-header: assets/workbench-tools.html
    filters:
      - assets/workbench-filters.lua

book:
  title: "The Carpentries Workbench"
  author: "Zhian N. Kamvar"
  date: "2022-04-29"
  chapters:
    - index.qmd
    - transition-guide.qmd
    - releases.qmd

website:
  title: "The Carpentries Workbench"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: faq.qmd
        text: FAQ
      - href: transition-schedule.qmd
        text: "**Transition Schedule**"
      - href: workflow-guide.qmd
        text: How The Workbench Works
      - href: transition-guide.qmd
        text: Transition Guide
      - text: "Contributor Guides"
        menu:
         - contributor/index.qmd
         - contributor/releases.qmd
         - contributor/flow.qmd
         - contributor/testing.qmd
    right:
      - icon: github
        href: 'https://github.com/carpentries/workbench'
        aria-label: Workbench GitHub





